### ISSUE TITLE
Add EBS Storage Classes

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/operationalizing-openshift-lab#13]
Let's shoot for 2 "classes" of storage. a "fast" and "slow"

**Comment by themoosman** [comment]
@etsauer Are you just looking for StorageClass templates?  i.e. one Fast and one Slow?

**Comment by etsauer** [comment]
@themoosman its a bit open for interpretation, but yeah I was thinking a "fast" and "slow" pointing to two different classes/flavors of EBS volumes
